version: '3.6'

services:

  api:
    image: node:19-alpine3.15
    container_name: tgd-node
    restart: always
    build: .
    ports:
      - 3000:3000
    environment:
     - NODE_ENV=local
     - ES_HOST=elasticsearch
     - NODE_PORT=3000
     - ELASTIC_URL=http://elasticsearch:9200
    volumes:
      - .:/usr/src/app/countries
    command: npm run start
    links:
        - Elasticsearch
    depends_on:
        - Elasticsearch
    networks: 
      - esnet

  Elasticsearch:
    container_name: tgd-elasticsearch
    image: elasticsearch:7.16.2
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    logging:
      driver: none
    ports:
      - 9200:9200
      - 9300:9300
    networks: 
      - esnet

  Logstash:
    image: logstash:7.16.2
    container_name: tgd-logstash
    restart: always
    volumes:
    - ./logstash/:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf 
    depends_on:
      - Elasticsearch
    ports:
    - '9600:9600'
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    networks:
      - esnet

  Kibana:
    image: kibana:7.16.2
    container_name: tgd-kibana
    restart: always       
    ports:
    - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200  
    depends_on:
      - Elasticsearch  
    networks:
      - esnet

volumes:
  elastic_data: {}

networks:
  esnet: