version: '3.6'

services:

  api:
    image: node:19-alpine3.15
    build: ./node_data/
    container_name: node-api
    restart: always
    ports:
      - 3000:3000
    environment:
     - NODE_ENV=local
     - ES_HOST=elasticsearch
     - NODE_PORT=3000
     - ELASTIC_URL=http://elasticsearch:9200
    volumes:
      - .:/usr/src/app/countries
    command: npm run start
    links:
        - Elasticsearch
    depends_on:
        - Elasticsearch
    networks: 
      - esnet

  Elasticsearch:
    container_name: elasticsearch-db
    image: elasticsearch:7.16.2
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    logging:
      driver: none
    ports:
      - 9200:9200
      - 9300:9300
    networks: 
      - esnet

  Logstash:
    image: logstash:7.16.2
    container_name: logstash
    restart: always
    volumes:
    - ./logstash/:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf 
    logging: 
      driver: "none"     
    depends_on:
      - Elasticsearch
    ports:
      - '9600:9600'
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    networks:
      - esnet

  Kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: always
    logging: 
      driver: "none"       
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200  
    depends_on:
      - Elasticsearch  
    networks:
      - esnet
  
  Python:
    image: python:3.10-slim
    build: ./python_cli/
    container_name: python-cli
    # entrypoint: ["sh", "-c", "docker" , "up" , "exec", "-it", "python-cli", "bash"]
    tty: true
    depends_on:
      - api
    networks:
      - esnet

volumes:
  elastic_data: {}

networks:
  esnet: